[workspace]
members = [
  "mdbook-exerciser",
  "mdbook-course",
  "src/types-and-values",
  "src/control-flow-basics",
  "src/tuples-and-arrays",
  "src/references",
  "src/user-defined-types",
  "src/methods-and-traits",
  "src/exercises",
  "src/bare-metal/useful-crates/allocator-example",
  "src/bare-metal/useful-crates/zerocopy-example",
  "src/exercises/concurrency/chat-async",
  "third_party/cxx/blobstore",
]
resolver = "2"
