[package]
name = "comprehensive-rust"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "luhn"
path = "day-1/luhn.rs"

[[bin]]
name = "points-polygons"
path = "day-3/points-polygons.rs"

[[bin]]
name = "safe-ffi-wrapper"
path = "day-3/safe-ffi-wrapper.rs"

[[bin]]
name = "dining-philosophers"
path = "concurrency/dining-philosophers.rs"

[[bin]]
name = "link-checker"
path = "concurrency/link-checker.rs"

[dependencies]
reqwest = { version = "0.11.12", features = ["blocking"] }
scraper = "0.15.0"
thiserror = "1.0.37"

[dev-dependencies]
tempfile = "3.5.0"
