# Based on https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
name: Generate Course Schedule

on:
  pull_request:
    paths:
      - "src/**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust cache
        uses: ./.github/workflows/setup-rust-cache

      - name: Generate Schedule
        run: |
          mkdir -p ./course-schedule
          cargo run -p mdbook-course --bin course-schedule > course-schedule/schedule

      - uses: actions/upload-artifact@v4
        with:
          name: course-schedule
          path: course-schedule/
